name: Test Program Async

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./a3rt_talkpy
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Run Async Version
      env:
        TALK_API_KEY: ${{ secrets.TALK_API_KEY }}
      run:
        python example/async.py

